### PR TITLE
chore: remove bls precompiles

### PR DESCRIPTION
**Pull request by onbjerg**
These are now in revm

### CODE REVIEW

**Comment by fgimenez** [comment]
@onbjerg the current code already imports the precompiles from revm, the local version was removed here https://github.com/paradigmxyz/alphanet/pull/76

if we remove the module that imports them from revm the alphanet node won't have BLS precompiles, is that what we want?

**Comment by onbjerg** [comment]
correct, it won't have bls precompiles unless prague is activated. perhaps we hold off on this until we have an alphanet specific fork in a stable form.

**Comment by onbjerg** [comment]
re-opening this: if prague is enabled in the chainspec, these precompiles will be enabled as well. I also mapped prague to prague + eof in #102

**Comment by onbjerg** [comment]
I've updated the genesis to enable prague by default in e79b976 in this PR

**Review by fgimenez — APPROVED** [review]
lgtm

**Pull request merged**
