### PR TITLE
test: add 3074 send eth integration test

### PR DESCRIPTION
**Pull request by fgimenez**
Adds a 3074 integration test to exercise the example described in #68. 

This required first to modify the test invoker, previously it always forwarded a zero value to the underlying auth/authcall wrapper contract, now there's an additional `value` parameter in `sponsorCall`. The smart contract artifacts are rebuilt to reflect this new behaviour.

The test itself does this:

* Spins up an AlphaNet node
* Deploys the invoker contract using a deployer EOA with funds.
* Sets up a signer EOA with funds, asserts that balance is not zero, and stores this initial balance.
* Sets up a receiver EOA without funds, and asserts that its balance is zero.
* The signer account signs a commit with the receiver address and empty data.
* The deployer EOA calls `sponsorCall` including the signature, the receiver address and the amount to be sent
* After the transaction is verified to be successful there are two checks:
  * The receiver balance has been increased by the amount sent
  * The signer balance has been decreased by the amount sent

The test is passing, @jrachman can you please check if this test follows the same logic as the example you described in #68? Not the script part, of course, but the interaction with the AlphaNet node.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

**Comment by Jrachman** [comment]
@fgimenez this is good to me! i think there is probably something weird with how i am doing my custom genesis rust script which can be found [here](https://github.com/otim-xyz/alphanet/blob/main/examples/custom-genesis-dev-node.rs). how do you populate an account with eth at genesis?

**Comment by fgimenez** [comment]
@Jrachman not sure, I've started locally a node using your example https://github.com/otim-xyz/alphanet/blob/main/examples/custom-genesis-dev-node.rs, run the integration test in this PR against it and everything worked fine, you can give it a try applying this patch to this branch:
```diff
diff --git a/crates/testing/src/tests.rs b/crates/testing/src/tests.rs
index 3d2427a..e022d91 100644
--- a/crates/testing/src/tests.rs
+++ b/crates/testing/src/tests.rs
@@ -126,6 +126,7 @@ async fn test_eip3074_send_eth() {
     let tasks = TaskManager::current();
     let test_suite = TestSuite::new();
 
+    /*
     // spin up alphanet node
     let chain_spec = Lazy::force(&DEV).clone();
     let node_config = NodeConfig::test()
@@ -140,6 +141,8 @@ async fn test_eip3074_send_eth() {
         .unwrap();
 
     let rpc_url = node.rpc_server_handle().http_url().unwrap();
+     */
+    let rpc_url = String::from("http://localhost:8545");
     let deployer = test_suite.signer();
     let provider = ProviderBuilder::new()
         .with_recommended_fillers()
```
and then running the test with:
```shell
$ RUST_LOG=info cargo +stable test -p alphanet-testing send_eth
```
The problem might be somewhere else, doesn't seem to be related to alphanet node.

**Comment by Jrachman** [comment]
@fgimenez hmmm there is something wrong with my [forge scripts](https://github.com/anton-rs/3074-invokers/blob/main/script/Execute.s.sol) then since the test is also working for me. id say we are good to go on this pr and will dig deeper into why my transactions are still failing. 👍

**Comment by fgimenez** [comment]
> @fgimenez hmmm there is something wrong with my [forge scripts](https://github.com/anton-rs/3074-invokers/blob/main/script/Execute.s.sol) then since the test is also working for me. id say we are good to go on this pr and will dig deeper into why my transactions are still failing. 👍

thx, if you have a way to reproduce the error I'd be happy to help if possible, we can continue the conversation in #68

**Pull request merged**
